import AppHeader from '@/components/navigation/app-header'
import { AppSidebar } from '@/components/navigation/app-side-bar'
import { SidebarProvider } from '@/components/ui/sidebar'
import type { Metadata } from 'next'
import { ThemeProvider as NextThemesProvider } from 'next-themes'
import './globals.css'
import CustomBreadCrumb from '@/components/custom-breadcrumb/custom-breadcrumb'

export const metadata: Metadata = {
  title: 'Template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`antialiased dark:bg-gray-950`}>
        <NextThemesProvider
          attribute={'class'}
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <div className='flex w-full flex-1 flex-col overflow-hidden'>
              <AppHeader />
              <main className='px-8'>
                <CustomBreadCrumb />
                {children}
              </main>
            </div>
          </SidebarProvider>
        </NextThemesProvider>
      </body>
    </html>
  )
}
